# Generated by Django 4.1.5 on 2023-01-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='plat',
            new_name='Plat',
        ),
    ]
