# Generated by Django 4.1.5 on 2023-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0002_rename_plat_menu_plat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteDuJjour',
            fields=[
                ('CarteDuJjourId', models.AutoField(primary_key=True, serialize=False)),
                ('Plat', models.CharField(max_length=500)),
                ('DateOfCreation', models.DateField()),
                ('PhotoFile', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=500)),
                ('ClientPrenom', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('CommandeId', models.AutoField(primary_key=True, serialize=False)),
                ('CommandeName', models.CharField(max_length=500)),
                ('Plat', models.CharField(max_length=500)),
                ('Desert', models.CharField(max_length=500)),
                ('Livreur', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('DesertId', models.AutoField(primary_key=True, serialize=False)),
                ('DesertName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('LivreurId', models.AutoField(primary_key=True, serialize=False)),
                ('LivreurName', models.CharField(max_length=500)),
                ('LivreurPrenom', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('PersonneId', models.AutoField(primary_key=True, serialize=False)),
                ('PersonneName', models.CharField(max_length=500)),
                ('PersonnePrenom', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='menu',
        ),
        migrations.RenameField(
            model_name='plat',
            old_name='PlatNameName',
            new_name='PlatName',
        ),
    ]
