# Generated by Django 4.1.5 on 2023-01-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0003_cartedujjour_client_commande_desert_livreur_personne_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarteDuJjour',
            new_name='CarteDuJour',
        ),
    ]
