# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0004_rename_cartedujjour_cartedujour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartedujour',
            name='Jours',
            field=models.CharField(default='Lundi', max_length=500),
        ),
        migrations.AddField(
            model_name='cartedujour',
            name='image',
            field=models.CharField(default='images/Ratatouille_001.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='ClientAdress',
            field=models.CharField(default='Ruil', max_length=500),
        ),
        migrations.AddField(
            model_name='desert',
            name='Price',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='desert',
            name='image',
            field=models.CharField(default='images/Ratatouille_001.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='plat',
            name='Price',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.CharField(default='images/Ratatouille_001.jpg', max_length=500),
        ),
    ]
